// <auto-generated />
using System;
using Azul.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Azul.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010190235_ModeloProveedor")]
    partial class ModeloProveedor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Azul.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Azul.Api.Entities.Offering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Offerings");
                });

            modelBuilder.Entity("Azul.Api.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FirstPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hours")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InstagramUsername")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhotoKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirstPublishedAt")
                        .IsDescending()
                        .HasFilter("\"Status\" = 'Published'");

                    b.HasIndex("InstagramUsername")
                        .IsUnique()
                        .HasDatabaseName("IX_Providers_InstagramUsername");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Providers", t =>
                        {
                            t.HasCheckConstraint("CK_Providers_Address_RequiredBusiness", "\"Type\" <> 'Business' OR \"Address\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Providers_DisplayName_NotBlank", "btrim(\"DisplayName\") <> ''");

                            t.HasCheckConstraint("CK_Providers_FirstPublishedAt", "\"Status\" <> 'Published' OR \"FirstPublishedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Providers_InstagramUsername_Lower", "\"InstagramUsername\" IS NULL OR \"InstagramUsername\" = lower(\"InstagramUsername\")");

                            t.HasCheckConstraint("CK_Providers_Name_OnlyIndividual", "\"Type\" = 'Individual' OR (\"FirstName\" IS NULL AND \"LastName\" IS NULL)");

                            t.HasCheckConstraint("CK_Providers_Name_RequiredIndividual", "\"Type\" <> 'Individual' OR (\"FirstName\" IS NOT NULL AND \"LastName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Providers_PhoneNumber", "\"PhoneNumber\" ~ '^\\+549\\d{10}$'");

                            t.HasCheckConstraint("CK_Providers_Status", "\"Status\" IN ('Pending', 'Published', 'Suspended')");

                            t.HasCheckConstraint("CK_Providers_Type", "\"Type\" IN ('Individual', 'Venture', 'Business')");
                        });
                });

            modelBuilder.Entity("Azul.Api.Entities.ProviderConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("ProviderConsents", t =>
                        {
                            t.HasCheckConstraint("CK_ProviderConsents_RevokedAt", "\"RevokedAt\" IS NULL OR \"RevokedAt\" >= \"AcceptedAt\"");
                        });
                });

            modelBuilder.Entity("Azul.Api.Entities.ProviderOffering", b =>
                {
                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProviderId", "OfferingId");

                    b.HasIndex("OfferingId");

                    b.ToTable("ProviderOfferings");
                });

            modelBuilder.Entity("Azul.Api.Entities.Offering", b =>
                {
                    b.HasOne("Azul.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Azul.Api.Entities.ProviderConsent", b =>
                {
                    b.HasOne("Azul.Api.Entities.Provider", "Provider")
                        .WithMany("Consents")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Azul.Api.Entities.ProviderOffering", b =>
                {
                    b.HasOne("Azul.Api.Entities.Offering", "Offering")
                        .WithMany()
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azul.Api.Entities.Provider", "Provider")
                        .WithMany("Offerings")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offering");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Azul.Api.Entities.Provider", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Offerings");
                });
#pragma warning restore 612, 618
        }
    }
}
